In [2]:
# NumPyをインポートするコード
import numpy as np

# AとBの行列を格納する多次元配列のコード
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# 行列の積の計算をするコード
C = np.dot(A, B)

# 計算結果を表示するコード
print("行列の積:")
print(C)

# 行列の要素の最大値を求めて表示するコード
max_value = np.max(C)
print("計算された行列の要素の最大値:", max_value)

行列の積:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
計算された行列の要素の最大値: 47
